### ISSUE TITLE
Client/Server Disconnect after opening tile entity

### ISSUE THREAD

**Issue by supercube9307** [STOKESTER/Plunger#2]
I don't really know what happened, but for a while now after I start up the world I can click on a tile entity (refined storage grid, chest, IF plant harvester, whatever) and do things but whenever I exit the screen the internal server stops and I can't open any other inventories, mine any blocks, or anything like that.
Latest log:
[latest.log](https://github.com/STOKESTER/Plunger/files/5350790/latest.log)

**Comment by tobi-polar** [comment]
Alot of errors relating to rendering, check your GPU driver is up to date, update the pack to latest version and if problem persists reopen this issue.
