### ISSUE TITLE
Crashes on server from Entity being ticked

### ISSUE THREAD

**Issue by Grothhar** [STOKESTER/Plunger#3]
It looks like some of it is from Guard Villagers but not sure about the rest.

[crash-2020-11-17_14.30.33-server.txt](https://github.com/STOKESTER/Plunger/files/5556134/crash-2020-11-17_14.30.33-server.txt)
[crash-2020-11-15_17.10.47-server.txt](https://github.com/STOKESTER/Plunger/files/5556135/crash-2020-11-15_17.10.47-server.txt)
[crash-2020-11-15_15.30.38-server.txt](https://github.com/STOKESTER/Plunger/files/5556136/crash-2020-11-15_15.30.38-server.txt)
[crash-2020-11-15_15.13.23-server.txt](https://github.com/STOKESTER/Plunger/files/5556137/crash-2020-11-15_15.13.23-server.txt)

**Comment by tobi-polar** [comment]
Your log mentions performant which isn't in the latest version of plunger. Please update your pack and if this issue continues re-open this ticket.
