### ISSUE TITLE
Can't mine Ender Essence and Azure Silver

### ISSUE THREAD

**Issue by Menelagg** [STOKESTER/Plunger#4]
Hi there,
My problem is, that I can't mine Ender Essence and Azure Silver. I tried it with a Tier 3 pickaxe and a normal diamond pickaxe. I would appreciate some help here :D Thanks

**Comment by tobi-polar** [comment]
Sorry for the extremely late reply, I doubt you still need an answer BUT
Ender essence requires a harvest level 4 pickaxe

![2021-05-16_23 09 24](https://user-images.githubusercontent.com/36657224/118398426-ebf7be00-b69b-11eb-982d-562b6e1b33f0.png)

and I was able to mine Azure with a cobalt pick

**Comment by tobi-polar** [comment]
I'll be adding [waila harvestability](https://www.curseforge.com/minecraft/mc-mods/waila-harvestability) in the next update (I could've sworn I already did, oops 😅)
